"""Economy: money, banks, goods, recipes and markets.

Money is integer minor units and always moves between two accounts — there is no way to
create or destroy value except through the explicit central-bank and default paths. Prices
are never generated by a model; they come out of supply, demand, inventory, transport,
production cost and expectations (spec section 12).
"""

from __future__ import annotations

import enum
from dataclasses import dataclass, field
from typing import ClassVar

from hydra.kernel.state import DomainState, register_domain


class OwnerKind(str, enum.Enum):
    PERSON = "person"
    HOUSEHOLD = "household"
    COMPANY = "company"
    GOVERNMENT = "government"
    BANK = "bank"
    CENTRAL_BANK = "central_bank"
    COHORT = "cohort"            # a statistical group of residents holding money together
    EXTERNAL = "external"        # rest of the world: imports and exports settle here


class GoodCategory(str, enum.Enum):
    ENERGY = "energy"
    UTILITY = "utility"
    FOOD = "food"
    MATERIAL = "material"
    COMPONENT = "component"
    CONSUMER = "consumer"
    SERVICE = "service"
    HOUSING = "housing"
    LOGISTICS = "logistics"


@dataclass(slots=True)
class Account:
    account_id: str
    owner_id: str
    owner_kind: OwnerKind
    bank_id: str = ""
    balance_minor: int = 0
    overdraft_minor: int = 0
    blocked: bool = False

    def available(self) -> int:
        return self.balance_minor + self.overdraft_minor


@dataclass(slots=True)
class Loan:
    loan_id: str
    borrower_id: str
    bank_id: str
    principal_minor: int
    outstanding_minor: int
    annual_rate: float
    issued_tick: int
    term_days: int
    next_payment_tick: int
    payment_minor: int = 0
    missed_payments: int = 0
    defaulted: bool = False


@dataclass(slots=True)
class Bank:
    bank_id: str
    name: str
    account_id: str
    capital_minor: int
    deposits_minor: int = 0
    loans_minor: int = 0
    reserve_ratio: float = 0.12
    spread: float = 0.035
    loan_ids: list[str] = field(default_factory=list)
    npl_minor: int = 0
    risk_appetite: float = 0.5


@dataclass(slots=True)
class Good:
    code: str
    name: str
    category: GoodCategory
    unit: str
    base_price_minor: int
    storable: bool = True
    cpi_weight: float = 0.0
    essential: bool = False
    cost_based: bool = True     # False = price set by scarcity alone (housing, land)
    perishable_daily: float = 0.0   # share of unsold stock that expires each day
    elasticity: float = 0.4         # how far demand falls when the price rises


@dataclass(slots=True)
class Recipe:
    """Bill of materials (spec section 13)."""

    output_code: str
    output_qty: float
    inputs: dict[str, float] = field(default_factory=dict)
    labour_hours: float = 0.0
    energy_kwh: float = 0.0
    logistics: float = 0.0


@dataclass(slots=True)
class Market:
    code: str
    price_minor: int
    previous_price_minor: int = 0
    supply: float = 0.0
    demand: float = 0.0
    inventory: float = 0.0
    transacted: float = 0.0
    unmet_demand: float = 0.0
    last_demand: float = 0.0            # demand measured in the cycle that just closed
    demand_ema: float = 0.0             # smoothed demand, for systems that size physical capacity
    cost_override_minor: int = 0        # set by a physical system (e.g. marginal generation)
    unit_cost_minor: int = 0
    expectation: float = 0.0            # -1 falling .. +1 rising, drives hoarding & pricing
    price_history: list[int] = field(default_factory=list)
    shortage_ticks: int = 0

    def record_price(self, limit: int = 240) -> None:
        self.price_history.append(self.price_minor)
        if len(self.price_history) > limit:
            del self.price_history[: len(self.price_history) - limit]


@register_domain
@dataclass(slots=True)
class EconomyState(DomainState):
    DOMAIN: ClassVar[str] = "economy"

    currency_code: str = "HYD"
    accounts: dict[str, Account] = field(default_factory=dict)
    banks: dict[str, Bank] = field(default_factory=dict)
    loans: dict[str, Loan] = field(default_factory=dict)
    goods: dict[str, Good] = field(default_factory=dict)
    recipes: dict[str, Recipe] = field(default_factory=dict)
    markets: dict[str, Market] = field(default_factory=dict)
    central_bank_account_id: str = ""
    external_account_id: str = ""
    escrow_account_id: str = ""       # holds buyer money until producers are paid
    imports_minor: int = 0
    exports_minor: int = 0
    policy_rate: float = 0.04
    cpi: float = 1.0
    cpi_base: dict[str, int] = field(default_factory=dict)
    inflation_annual: float = 0.0
    cpi_history: list[float] = field(default_factory=list)
    gdp_minor: int = 0
    gdp_history: list[int] = field(default_factory=list)
    wage_index: float = 1.0
    unemployment_rate: float = 0.06
    next_account_index: int = 0
    next_loan_index: int = 0
    money_supply_minor: int = 0
    transactions: int = 0
    volume_minor: int = 0

    # -- accounts -----------------------------------------------------------------
    def open_account(self, owner_id: str, kind: OwnerKind, bank_id: str = "", balance_minor: int = 0,
                     overdraft_minor: int = 0) -> Account:
        self.next_account_index += 1
        account = Account(
            account_id=f"acct_{self.next_account_index:06d}",
            owner_id=owner_id,
            owner_kind=kind,
            bank_id=bank_id,
            balance_minor=balance_minor,
            overdraft_minor=overdraft_minor,
        )
        self.accounts[account.account_id] = account
        self.money_supply_minor += balance_minor
        return account

    def balance(self, account_id: str) -> int:
        account = self.accounts.get(account_id)
        return account.balance_minor if account else 0

    def market(self, code: str) -> Market:
        return self.markets[code]
