#!/usr/bin/env python3
"""Generate ``docs/CONTRACTS.md`` from the running system registry.

Rule 35.13 asks every subsystem to have an explicit input/output contract. Rather than keeping
a table in a document that quietly drifts from the code, this reads the contracts the kernel
actually enforces and writes the document from them.

    python scripts/dump_contracts.py
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
for package in sorted((ROOT / "packages").iterdir()):
    if package.is_dir() and (package / "hydra").is_dir():
        sys.path.insert(0, str(package))

from hydra.kernel.clock import TICKS_PER_DAY, TICKS_PER_HOUR, TICKS_PER_MONTH  # noqa: E402
from hydra.kernel.config import WorldConfig  # noqa: E402
from hydra.world import build_registry  # noqa: E402


def cadence_label(ticks: int) -> str:
    if ticks <= 0:
        return "event-driven"
    if ticks == 1:
        return "every tick (10 min)"
    if ticks % TICKS_PER_MONTH == 0:
        return f"{ticks // TICKS_PER_MONTH} month(s)"
    if ticks % TICKS_PER_DAY == 0:
        return f"{ticks // TICKS_PER_DAY} day(s)"
    if ticks % TICKS_PER_HOUR == 0:
        return f"{ticks // TICKS_PER_HOUR} hour(s)"
    return f"{ticks} ticks"


def main() -> int:
    registry = build_registry(WorldConfig())
    lines = [
        "# Subsystem contracts",
        "",
        "Generated by `python scripts/dump_contracts.py` from the system registry — this is",
        "what the kernel enforces, not a description of it. With `strict_contracts` enabled a",
        "system that writes a domain missing from its `writes` column is recorded as a failure",
        "and quarantined.",
        "",
        "Phases run in a fixed order within every tick:",
        "`ENVIRONMENT → AGENTS → INSTITUTIONS → MARKETS → PHYSICAL → INFORMATION → SLOW`.",
        "",
    ]
    current_phase = None
    for spec in registry.contracts():
        if spec.phase != current_phase:
            current_phase = spec.phase
            lines += [
                "",
                f"## {int(spec.phase)}. {spec.phase.name}",
                "",
                "| System | Cadence | Reads | Writes | Emits | Consumes |",
                "|---|---|---|---|---|---|",
            ]
        lines.append(
            "| `{name}` | {cadence} | {reads} | {writes} | {emits} | {consumes} |".format(
                name=spec.name,
                cadence=cadence_label(spec.cadence_ticks),
                reads=", ".join(spec.reads) or "—",
                writes=", ".join(spec.writes) or "—",
                emits=", ".join(spec.emits) or "—",
                consumes=", ".join(spec.consumes) or "—",
            )
        )
    lines += ["", "## Descriptions", ""]
    for spec in registry.contracts():
        lines.append(f"- **`{spec.name}`** — {spec.description}")
    lines.append("")

    target = ROOT / "docs" / "CONTRACTS.md"
    target.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {target} ({len(registry.contracts())} systems)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
